### ISSUE TITLE
Gradle build faild

### ISSUE THREAD

**Issue by jumpfunky** [eseifert/gral#1]
Hi,

I tried to build a jar file using gradle (2.3). However, it fails:

>Download https://jcenter.bintray.com/com/google/code/google-collections/google-collect/snapshot->20080530/google-collect-snapshot-20080530.jar
>Download https://jcenter.bintray.com/stax/stax-api/1.0.1/stax-api-1.0.1.jar
>Download https://jcenter.bintray.com/org/sonatype/sisu/sisu-guice/2.9.1/sisu-guice-2.9.1-noaop.jar
>Download https://jcenter.bintray.com/log4j/log4j/1.2.12/log4j-1.2.12.jar
>Download https://jcenter.bintray.com/commons-logging/commons-logging-api/1.1/commons-logging->api-1.1.jar
>fatal: Not a git repository (or any of the parent directories): .git
>FAILURE: Build failed with an exception.
>* Where:
>Build file '/home/thorsten/Downloads/gral-master/build.gradle' line: 108
>* What went wrong:
>A problem occurred evaluating root project 'GRAL'.
> Process 'command 'git'' finished with non-zero exit value 128

The output --stacktrace is:
>* Exception is:
>org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'GRAL'.
>	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
>	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:154)
>	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
>	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
>	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
>	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
>	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
>	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
>	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
>	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
>	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
>	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
>	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
>	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
>	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
>	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
>	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
>	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
>	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
>	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
>	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
>	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
>	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
>	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
>	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
>	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
>	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
>	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
>	at org.gradle.launcher.Main.doAction(Main.java:33)
>	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
>	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
>	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
>Caused by: org.gradle.process.internal.ExecException: Process 'command 'git'' finished with non-zero exit value 128
>	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
>	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
>	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:151)
>	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:780)
>	at org.gradle.groovy.scripts.DefaultScript.exec(DefaultScript.java:201)
>	at org.gradle.api.Script$exec$0.callCurrent(Unknown Source)
>	at build_7ywaf999q0ful94t8s3nkopek.getVersionString(/home/thorsten/Downloads/gral-master/build.gradle:108)
>	at build_7ywaf999q0ful94t8s3nkopek$_run_closure1.doCall(/home/thorsten/Downloads/gral-master/build.gradle:3)
>	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
>	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
>	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
>	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:812)
>	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:817)
>	at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:804)
>	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
>	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
>	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
>	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
>	at build_7ywaf999q0ful94t8s3nkopek.run(/home/thorsten/Downloads/gral-master/build.gradle:1)
>	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
>	... 32 more

The output of --debug is:
>[...]
>15:14:32.782 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
>15:14:32.783 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'git'.
>15:14:32.788 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
>15:14:32.789 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
>15:14:32.789 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'git''
>15:14:32.792 [ERROR] [system.err] fatal: Not a git repository (or any of the parent directories): .git
>15:14:32.795 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
>15:14:32.796 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'git'' finished with exit value 128 (state: FAILED)
>15:14:32.798 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 1.349 secs
>15:14:32.813 [ERROR] [org.gradle.BuildExceptionReporter] 
>15:14:32.813 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
>15:14:32.814 [ERROR] [org.gradle.BuildExceptionReporter] 
>15:14:32.815 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
>15:14:32.815 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/home/thorsten/Downloads/gral-master/build.gradle' line: 108
>15:14:32.815 [ERROR] [org.gradle.BuildExceptionReporter] 
>15:14:32.816 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
>15:14:32.816 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'GRAL'.
>15:14:32.817 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'git'' finished with non-zero exit value 128
>15:14:32.817 [ERROR] [org.gradle.BuildExceptionReporter] 
>15:14:32.817 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
>15:14:32.818 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
>15:14:32.819 [LIFECYCLE] [org.gradle.BuildResultLogger] 
>15:14:32.820 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
>15:14:32.821 [LIFECYCLE] [org.gradle.BuildResultLogger] 
>15:14:32.822 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 3.922 secs
>15:14:32.825 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for settings file '/home/thorsten/Downloads/gral-master/settings.gradle' (/home/>thorsten/.gradle/caches/2.3/scripts/settings_9sdx9cd1l1b5yi58opf1ubpx0/SettingsScript/buildscript).
>15:14:32.826 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for settings file '/home/thorsten/Downloads/gral-master/settings.gradle' (/home/>thorsten/.gradle/caches/2.3/scripts/settings_9sdx9cd1l1b5yi58opf1ubpx0/SettingsScript/no_buildscript).
>[...]

**Comment by seifertm** [comment]
Thanks for the report and the error logs.

The Gradle build of GRAL uses git to determine the current build number. It basically calls "git describe --tags" to retrieve a unique version number for any commit.

By the looks of it, the git command is run, but does not find a git repository.

As a quick workaround, you could remove the git command from getVersionString() and return a fixed value, such as "0.11-SNAPSHOT".

How are you initiating the build? Are you calling it via the command line or an IDE?
Do you build GRAL as a standalone project or as a dependency?

**Comment by jumpfunky** [comment]
Hi! Commenting out some lines and return the fixed value helps. It works now! Thank you very much for the fast response. I've used the command line!

**Comment by seifertm** [comment]
According to the error logs, it seems that there was a problem with the build environment you were using. Otherwise, feel free to reopen the issue.

**Comment by CodingForAndroid** [comment]
i've got the same problem when compile  Glide project   
' Error:Process 'command 'git'' finished with non-zero exit value 128 '

ps:i build Glide with AndroidStudio.
hope for you answer .

**Comment by CodingForAndroid** [comment]
@seifertm 
i have the same problem  when build Glide  via AndroidStudio,
'Error:Process 'command 'git'' finished with non-zero exit value 128'
ilooked your answer for 'thorstenwagner' ,but i don't know how to solve, hope  ur answer ,thank u.

**Comment by seifertm** [comment]
@CodingForAndroid It seems like git is not correctly installed on your system. The Gradle script calls `git describe` on the command line to determine the correct version of the build.

Note that it is not enough that you can use git in your IDE. You have to install it on your system so that the `git` command can be called directly from the console.

**Comment by CodingForAndroid** [comment]
@seifertm  thx
