### ISSUE TITLE
Add jar with source code for gral-core-0.10 to Maven repository

### ISSUE THREAD

**Issue by eseifert** [eseifert/gral#114]
In the repository

http://mvn.erichseifert.de/maven2

the source jar for gral-core 0.10 is missing. It would be great if it could be added

 _Imported from trac ticket #115,  created by msteiger on 08-04-2014 at 18:30, last modified: 08-04-2014 at 18:30_

**Comment by seifertm** [comment]
Obsolete as of release 0.11.
Please use the more recent version of GRAL, if you require the source jar.
