### ISSUE TITLE
Charts exported as images  (BMP/PNG/GIF/JPEG) are of a poor quality

### ISSUE THREAD

**Issue by eseifert** [eseifert/gral#115]
Images created either by the Export option from the InteractivePanel or by the BitmapWriter are of a poor quality compared to the chart displayed in the interactive panel. Even upgrading the quality to QUALITY in the DrawingContext class does not change anything.
This problem prevents me from using GRAL in my software.

 _Imported from trac ticket #116,  created by bfrezouls on 09-15-2014 at 21:52, last modified: 09-15-2014 at 22:55_

**Comment by eseifert** [comment]
Thanks for the report. I'll have a look at it tomorrow. Quality settings are a work in progress and aren't fully implemented yet. I'll try to work on it as soon as possible.

_Trac comment by eseifert on 09-15-2014 at 22:55_

**Comment by seifertm** [comment]
Already addressed by issue #110.
