### ISSUE TITLE
some JUnit test fails while building

### ISSUE THREAD

**Issue by cscheiblich** [eseifert/gral#122]
Hi there,

some easy JUnit tests on serialization are failing - in my case - while building with gradle:

java.lang.AssertionError: expected:<de.erichseifert.gral.graphics.Label@73fcd8fb> but was:<de.erichseifert.gral.graphics.Label@3a12dea3>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at de.erichseifert.gral.plots.axes.AbstractAxisRenderer2DTest.testSerialization(AbstractAxisRenderer2DTest.java:93)

https://github.com/eseifert/gral/blob/master/gral-core/src/test/java/de/erichseifert/gral/plots/axes/AbstractAxisRenderer2DTest.java

Hope helping you ...

Christian

**Comment by cscheiblich** [comment]
Hej, hej, was only that method seems to be not working ...

assertEquals(original.getLabel(), deserialized.getLabel());

some issues due to case sensitivity - I skipped that test???

Christian

**Comment by seifertm** [comment]
Hi Christian,

Thanks for the report!

I am pretty sure the failing test is related to #96. `Label` does not implement `Object.equals(Object)`, so after deserialisation, the equals check fails. In practice, the contents of the original Label and the deserialised one should be the same.

**Comment by cscheiblich** [comment]
Hi,

indeed - but that JUnit fails in my case while building (skipped it, to overcome building gral).

best
