### ISSUE TITLE
flattr link is 410

### ISSUE THREAD

**Issue by koppor** [eseifert/gral#125]
When clicking "Flattr this" on http://trac.erichseifert.de/gral, a 410 appears. (Link is http://flattr.com/thing/179251/GRAL-Java-plotting).

**Comment by eseifert** [comment]
Thanks for reporting! The button was used only once in the history of the project. Meanwhile the flattr account has been suspended because I haven't logged in for ages. I have removed the link from the front page now to prevent further confusion.
