### ISSUE TITLE
List of data points in window coordinates

### ISSUE THREAD

**Issue by lessthanoptimal** [eseifert/gral#128]
I would like to add user interaction and determine which data point a user has selected.  I can add a mouse listener to an outside container but as far as I can tell there is no way to get the pixel coordinate of data points.  So I would like something like getRenderDataLocation() and have that return a list with  (index,pixel x,pixel y)

**Comment by lessthanoptimal** [comment]
Here's an example of an alternative way to accomplish this from JFreeChart

double chartX = plot.getDomainAxis().java2DToValue(p.getX(), plotArea, plot.getDomainAxisEdge());
double chartY = plot.getRangeAxis().java2DToValue(p.getY(), plotArea, plot.getRangeAxisEdge());

**Comment by eseifert** [comment]
The projection from data to pixel coordinates is handled by ``AxisRenderer.worldToView(Axis axis, Number value, boolean extrapolate)``. In GRAL the example above would look similar to this:
```java
double chartX = plot.getAxisRenderer(Axis.X).worldToView(plot.getAxis(Axis.X), p.getX(), false);
double chartY = plot.getAxisRenderer(Axis.Y).worldToView(plot.getAxis(Axis.Y), p.getY(), false);
```
If this answers your question, I will add it to the how-to section of the wiki and close this issue.

**Comment by lessthanoptimal** [comment]
Ended up being a bit more involved to get worldToView() to produce coordinates in window coordinates:

```
double height = plot.getPlotArea().getHeight();
double offX = plot.getPlotArea().getX();
double offY = plot.getPlotArea().getY();
					
double pixelX = plot.getAxisRenderer(XYPlot.AXIS_X).worldToView(axisX,v0,true);
double pixelY = plot.getAxisRenderer(XYPlot.AXIS_Y).worldToView(axisY,v1,true);

pixelX = offX + pixelX;
pixelY = offY + height - pixelY;
```

Adding an example which goes in both directions would be great in the howtos.  Thanks!

**Comment by eseifert** [comment]
I have added this as a how-to article now: https://github.com/eseifert/gral/wiki/howto-pixel-coordinates-of-points
