### ISSUE TITLE
Draw Distinct Line Plot on BarPlot

### ISSUE THREAD

**Issue by laxatives** [eseifert/gral#129]
Is it possible to draw a distinct line plot using one data set over on a ``BarPlot`` with bars from a different data set? I've tried setting the bar's color to transparent from the data producing the line plot, but GRAL seems to ignore the alpha channel. I've also tried to change the ordering such that the smaller bars appear in front of the large bars from the line plot, but GRAL seems to prefer drawing taller bars in front of smaller ones. Is there a solution I'm missing?

```java
DataTable results = new DataTable(Double.class, Integer.class, Double.class, 
        Integer.class, Double.class, Integer.class, Double.class);

DataSeries fs = new DataSeries(results, 0, 1); // barA
DataSeries hfs = new DataSeries(results, 0, 6); // lineA
DataSeries rs = new DataSeries(results, 2, 3);  // barB
DataSeries hrs = new DataSeries(results, 2, 6); // lineB
DataSeries ms = new DataSeries(results, 4, 5); // barC
DataSeries hms = new DataSeries(results, 4, 6); // lineC

System.out.println("\tPlotting results...");
BarPlot plot = new BarPlot(fs, hfs, rs, hrs, ms, hms);
plot.setInsets(new Insets2D.Double(20.0, 40.0, 40.0, 40.0));
plot.setBarWidth(BAR_WIDTH);

BarRenderer fsRenderer = new BarRenderer(plot);
fsRenderer.setColor(PlotUtil.BLUE);
fsRenderer.setValueVisible(true);
plot.addPointRenderer(fs, fsRenderer);
BarRenderer rsRenderer = new BarRenderer(plot);
rsRenderer.setColor(PlotUtil.GOLD);
rsRenderer.setValueVisible(true);
plot.addPointRenderer(rs, rsRenderer);
BarRenderer msRenderer = new BarRenderer(plot);
msRenderer.setColor(PlotUtil.GREEN);
msRenderer.setValueVisible(true);
plot.addPointRenderer(ms, msRenderer);

BarRenderer hsRenderer = new BarRenderer(plot);
hsRenderer.setValueVisible(true);
hsRenderer.setValueLocation(Location.SOUTH);
plot.addPointRenderer(hfs,  hsRenderer);
plot.addPointRenderer(hrs,  hsRenderer);
plot.addPointRenderer(hms,  hsRenderer);
LineRenderer lineRenderer = new DefaultLineRenderer2D();
lineRenderer.setColor(PlotUtil.RED);
plot.setLineRenderers(hfs, lineRenderer);
plot.setLineRenderers(hrs, lineRenderer);
plot.setLineRenderers(hms, lineRenderer);

PlotUtil.drawPlot(plot);
```

**Comment by seifertm** [comment]
As far as I understand, you are having two problems here:

1. Your data series are painted in the wrong order
2. `BarPlot` does not display Colors with an alpha value correclty

Is this correct so far?

I cannot verify issue 2, so I need some more info on this. A screenshot helps greatly, if that is possible.

Regarding issue 1:
From your description, you know that the order in which `DataSource`s are added to the plot is relevant, but GRAL seems to ignore the order. I played around a bit and it seems you ran into a bug here. At some point, the ordering of `DataSource`s in `Plot` gets lost...

**Comment by seifertm** [comment]
… or not. I just noticed that the piece of code does what it should: The order of data series in a `Plot` should be preserved.

Can you attach a screen shot? This makes it easier for me to help out.

**Comment by seifertm** [comment]
Are there any news on this issue, @laxatives?

**Comment by seifertm** [comment]
I will close this issue for the time being. I am sorry I couldn't help you, but I am having problems reproducing your issues.

Feel free to reopen this issue any time, if you are still experiencing problems.
