### ISSUE TITLE
Is there more documents?

### ISSUE THREAD

**Issue by anysome** [eseifert/gral#132]
Hi, I'm searching for server chart render then met this greet thing. And We need some comparable bar plots, like these, 
![img01](https://cloud.githubusercontent.com/assets/233960/14269964/330acd14-fb1c-11e5-86cf-4bac95c4cfdd.jpg)
![img02](https://cloud.githubusercontent.com/assets/233960/14269965/33d52668-fb1c-11e5-9fa5-b69c4b22d9c9.jpg)
Trying examples and add another dataTable but not match, do I doing wrong, or some docs for fixing it?

**Comment by seifertm** [comment]
At the moment, this is not possible with GRAL, sorry.

It has been on the feature list for some time, though: #20
