### ISSUE TITLE
I accendentally messed up the chart comparison Wiki page

### ISSUE THREAD

**Issue by timmolter** [eseifert/gral#141]
My apologies!

<https://github.com/eseifert/gral/wiki/comparison>

I made super basic edit on the XChart lib, so I'm really not sure why it's not displaying anything on the page any more.

**Comment by eseifert** [comment]
No problem, I fixed it. Unfortunately, the tablet is quite big and the formatting is a little fragile.

**Comment by timmolter** [comment]
Thanks!
