### ISSUE TITLE
Wiki outdated for XYplot?

### ISSUE THREAD

**Issue by thhart** [eseifert/gral#159]
Hi, I tried to test the following code, but it does not work in version 0.11:

https://github.com/eseifert/gral/wiki/xyplot

Following methods are not found, for example:

```
plot.setLineRenderer(data, lines);
Color color = new Color(0.0f, 0.3f, 1.0f);
plot.getPointRenderer(data).setColor(color);
plot.getLineRenderer(data).setColor(color);
```

**Comment by eseifert** [comment]
Thanks for the report. I just fixed the example on the wiki page.
