### ISSUE TITLE
Dead link to API documentation

### ISSUE THREAD

**Issue by pschwede** [eseifert/gral#174]
Hi. I get a 404 if I request http://www.erichseifert.de/dev/gral/latest/apidocs/index.html .

**Comment by eseifert** [comment]
It seems that something is going wrong when redirecting to https. I’ll look into it.

**Comment by GreenGary** [comment]
Works for me. Temporary issue or has it been fixed?

**Comment by eseifert** [comment]
Thanks for having a look @GreenGary . I changed the redirection to HTTPS in the meantime and it should work as expected again.
