### ISSUE TITLE
How to put names of bars below the x-axis

### ISSUE THREAD

**Issue by DerTricker** [eseifert/gral#176]
Hi everyone,

in the example Bar Plot (SimpleBarPlot.java), each bar is named with a month. I would like to create a similar bar plot, but since the names I use are too long, I would prefere to have them below my bars (instead of the 0.1, 0.2 etc). How can I achieve this?

I am looking forward to an answer :)

**Comment by DerTricker** [comment]
I found it out. If anyone is interested:

`BarRenderer pointRenderer = (BarRenderer) plot.getPointRenderers(data).get(0);
pointRenderer.setValueLocation(Location.SOUTH);`

**Comment by eseifert** [comment]
Thanks! Sorry for being too late. I’m glad you could solve it though. I added your solution as a stub to the How-Tos section in the Wiki: https://github.com/eseifert/gral/wiki/how-to-bar-plot-labels-below-xaxis
