### ISSUE TITLE
Nullpointerexception in DataTable/set

### ISSUE THREAD

**Issue by sandy1931** [eseifert/gral#2]
Problem: Calling method 'equals' causes a nullpointerexception in case 'old' hasn't been set before and therefore being null.

    @SuppressWarnings("unchecked")
	public <T> Comparable<T> set(int col, int row, Comparable<T> value) {
		Comparable<T> old;
		DataChangeEvent event = null;
		synchronized (this) {
			old = (Comparable<T>) get(col, row);
			if (!old.equals(value)) {
				rows.get(row)[col] = value;
				event = new DataChangeEvent(this, col, row, old, value);
			}
		}
		if (event != null) {
			notifyDataUpdated(event);
		}
		return old;
	}
	
	

Solution:
	
    @SuppressWarnings("unchecked")
	public <T> Comparable<T> set(int col, int row, Comparable<T> value) {
		Comparable<T> old;
		DataChangeEvent event = null;
		synchronized (this) {
			old = (Comparable<T>) get(col, row);
			if (old == null || !old.equals(value)) {
				rows.get(row)[col] = value;
				event = new DataChangeEvent(this, col, row, old, value);
			}
		}
		if (event != null) {
			notifyDataUpdated(event);
		}
		return old;
	}

**Comment by seifertm** [comment]
Thanks for the report!

This issue has been fixed in commit 7790286a284c327c76f23a1114849440d69f6005.

By the way, never mind the previous mention. It occurred due to the import of the tickets from the old Trac issue tracker.
