### ISSUE TITLE
Lazy computation of statistical data

### ISSUE THREAD

**Issue by seifertm** [eseifert/gral#41]
Just like more complex computations like median or mean, all other statistical data that is not needed to draw a graph should be calculated on-demand.

 _Imported from trac ticket #38,  created by mseifert on 04-17-2011 at 13:24, last modified: 04-22-2011 at 15:49_

**Comment by seifertm** [comment]
Works as of [r360](None/changeset/360/historical).

However the above ticket description was not completely implemented, because the sum, sum of squares, ... are still not calculated on-demand. An on-demand implementation would have to go through all table cells to do the calculation, which requires more computing time the larger the data sets are. Adjusting the sums when values are changed slows down the add/update/remove process by a constant amount of time instead.

_Trac comment by mseifert on 04-18-2011 at 19:42_

**Comment by seifertm** [comment]
The cache for the sum, sum of squares, ... might not be updated when values are changed or removed.

_Trac comment by mseifert on 04-18-2011 at 19:57_

**Comment by eseifert** [comment]
As of [r363](None/changeset/363/historical) all statistics are calculated in a lazy way.

_Trac comment by eseifert on 04-22-2011 at 15:48_
