### ISSUE TITLE
Feature Request around graph titles

### ISSUE THREAD

**Issue by eseifert** [eseifert/gral#55]
I'm desiring the ability to modify the title background colour (so I can align it with the background colour of the graph area) and the title text colour.

thanks and regards,

Linds.

 _Imported from trac ticket #56,  created by LindsayBradford on 05-27-2012 at 06:06, last modified: 01-24-2014 at 12:54_

**Comment by seifertm** [comment]
Setting the text color of a `Label` is already possible using `Label.setColor(Paint)`.

From now on, `Label` will also support a property for specifying the background color using `Label.setBackground(Paint)`.

_Trac comment by mseifert on 01-24-2014 at 12:54_
