### ISSUE TITLE
More interactions for InteractivePanel

### ISSUE THREAD

**Issue by eseifert** [eseifert/gral#7]
InteractivePanel should get more interactive. Examples:
 - allow zooming with click, lasso, or by mouse wheel
 - Set scale of axes.

 _Imported from trac ticket #4,  created by eseifert on 05-23-2010 at 14:14, last modified: 05-30-2010 at 18:47_

**Comment by eseifert** [comment]
Created the new class PlotNavigator to allow for additional navigation. Lasso and interactively changing axis scale is still missing. Will open a new ticket if necessary.

_Trac comment by eseifert on 05-25-2010 at 16:33_

**Comment by seifertm** [comment]
* Zooming via mouse wheel works
 * Moving the plot works

_Trac comment by mseifert on 05-30-2010 at 18:47_
